### PR TITLE
Update imguralbum.py

### PR DESCRIPTION
**Pull request by vinieich**
I changed imageIDs from list to set, so it doesn't return duplicate imgs ever.
This is my first collaboration, sorry if this is not the way and please contact me.

### CODE REVIEW

**Comment by zuik** [comment]
Ditto on this as it would solve issue #37

**Comment by szero** [comment]
This was already done here #26

**Comment by Kagami** [comment]
@Szero your version gives the following error:

```bash
$ ~/imguralbum.py http://imgur.com/a/uOOju           
Traceback (most recent call last):
  File "/home/user/imguralbum.py", line 207, in <module>
    downloader = ImgurAlbumDownloader(args[1])
  File "/home/user/imguralbum.py", line 96, in __init__
    for i in self.imageIDs:
AttributeError: 'ImgurAlbumDownloader' object has no attribute 'imageIDs'
```
This one works, so :+1:

**Comment by szero** [comment]
@Kagami Thanks, I updated it so it works like it should now.

**Comment by vinieich** [comment]
Closing to prevent duplication as @Szero too has a working version.

**Pull request closed without merging**
